<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="row">
    <div class="col-lg-3 col-6">
        <div class="small-box bg-info">
            <a href="#" class="small-box">
                <div class="inner">
                    <h3>$500</h3>
                    <p>Pago Semanal</p>


                </div>
            </a>
            <div class="icon">
                <i class="ion ion-bag"></i>
            </div>
            <a href="#" class="small-box-footer">Otra cantidad <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>

    <div class="col-lg-3 col-6">

        <div class="small-box bg-info">
            <div class="inner">
                <h3>$3,500<sup style="font-size: 20px">%</sup></h3>
                <p>Ingresos</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="#" class="small-box-footer">Otra cantidad <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>

    <div class="col-lg-3 col-6">

        <div class="small-box bg-info">
            <div class="inner">
                <h3>44</h3>
                <p>User Registrations</p>
            </div>
            <div class="icon">
                <i class="ion ion-person-add"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>

    <div class="col-lg-3 col-6">

        <div class="small-box bg-info">
            <div class="inner">
                <h3>65</h3>
                <p>Unique Visitors</p>
            </div>
            <div class="icon">
                <i class="ion ion-pie-graph"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>

</div>


<div class="row">
    <div class="col-md-8">
        <div class="card card-widget">
            <div class="card-header">
                <div class="user-block">
                    <img class="img-circle" src="../dist/img/user1-128x128.jpg" alt="User Image">
                    <span class="username"><a href="#">Selecciona la cuota de recuperación</a></span>
                    <span class="description">Pagos de servicios</span>
                </div>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" title="Mark as read">
                        <i class="far fa-circle"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>

            </div>
            <div class="card-body" style="display: block;">
                <div class="row">
                    <!-- Costo de tratamiento $500 -->
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-info">
                            <a href="#" class="small-box">
                                <div class="inner">
                                    <h3>$500</h3>
                                    <p>Pago Semanal</p>
                                </div>
                            </a>
                            <div class="icon">
                                <i class="ion ion-bag"></i>
                            </div>
                            <a href="#" class="small-box-footer">Otra cantidad <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- Costo de tratamiento $150 -->
                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-info">
                            <a href="#" class="small-box">
                                <div class="inner">
                                    <h3>$150</h3>
                                    <p>Cafe y Cigarros</p>
                                </div>
                            </a>
                            <div class="icon">
                                <i class="ion ion-bag"></i>
                            </div>
                            <a href="#" class="small-box-footer">Otra cantidad <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <div id="divIngreso" class="col-lg-3 col-6">
                        <div class="small-box bg-info">
                            <a href="#" class="small-box">
                                <div class="inner">
                                    <h3>$3,500</h3>
                                    <p>Ingreso paciente</p>
                                </div>
                            </a>
                            <div class="icon">
                                <i class="ion ion-bag"></i>
                            </div>
                            <a href="#" class="small-box-footer">Otra cantidad <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>

                    <!--<div class="col-sm-4 border-right">
                        <div class="description-block">
                            <h5 class="description-header">3,200</h5>
                            <span class="description-text">SALES</span>
                        </div>

                    </div>

                    <div class="col-sm-4 border-right">
                        <div class="description-block">
                            <h5 class="description-header">13,000</h5>
                            <span class="description-text">FOLLOWERS</span>
                        </div>

                    </div>

                    <div class="col-sm-4">
                        <div class="description-block">
                            <h5 class="description-header">35</h5>
                            <span class="description-text">PRODUCTS</span>
                        </div>
                    </div>-->
                </div>
            </div>

            <div class="card-footer card-comments" style="display: block;">
                <div class="card-comment">

                    <img class="img-circle img-sm" src="/sysclinica/public/dist/img/user3-128x128.jpg" alt="User Image">
                    <div class="comment-text">
                        <span class="username">
                            Maria Gonzales
                            <span class="text-muted float-right">8:03 PM Today</span>
                        </span>
                        It is a long established fact that a reader will be distracted
                        by the readable content of a page when looking at its layout.
                    </div>

                </div>

                <div class="card-comment">

                    <img class="img-circle img-sm" src="../dist/img/user4-128x128.jpg" alt="User Image">
                    <div class="comment-text">
                        <span class="username">
                            Luna Stark
                            <span class="text-muted float-right">8:03 PM Today</span>
                        </span>
                        It is a long established fact that a reader will be distracted
                        by the readable content of a page when looking at its layout.
                    </div>

                </div>

            </div>

            <div class="card-footer" style="display: block;">
                <form action="#" method="post">
                    <img class="img-fluid img-circle img-sm" src="../dist/img/user4-128x128.jpg" alt="Alt Text">

                    <div class="img-push">
                        <input type="text" class="form-control form-control-sm" placeholder="Press enter to post comment">
                    </div>
                </form>
            </div>

        </div>

    </div>

    <div class="col-md-4">

        <div class="card card-widget">
            <div class="card-header">
                <div class="user-block">
                    <img class="img-circle" src="/sysclinica/public/dist/img/LogoRenovacion.png" alt="User Image">
                    <span class="username"><a href="#">Agregar servicio</a></span>
                    <span class="description">Utimo agregados 10:00 am</span>
                </div>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" title="Mark as read">
                        <i class="far fa-circle"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>

            </div>

            <div class="card-body" style="display: block;">
                <div id="addconte">
                    hola quitar esto
                </div>
 
            </div>
            <p>Far far away, behind the word mountains, far from the
                countries Vokalia and Consonantia, there live the blind
                texts. Separated they live in Bookmarksgrove right at</p>
            <p>the coast of the Semantics, a large language ocean.
                A small river named Duden flows by their place and supplies
                it with the necessary regelialia. It is a paradisematic
                country, in which roasted parts of sentences fly into
                your mouth.</p>

            <div class="attachment-block clearfix">
                <img class="attachment-img" src="../dist/img/photo1.png" alt="Attachment Image">
                <div class="attachment-pushed">
                    <h4 class="attachment-heading"><a href="https://www.lipsum.com/">Lorem ipsum text generator</a></h4>
                    <div class="attachment-text">
                        Description about the attachment can be placed here.
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry... <a href="#">more</a>
                    </div>

                </div>

            </div>


            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i> Share</button>
            <button type="button" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i> Like</button>
            <span class="float-right text-muted">45 likes - 2 comments</span>
        </div>

        <div class="card-footer card-comments" style="display: block;">
            <div class="card-comment">

                <img class="img-circle img-sm" src="../dist/img/user3-128x128.jpg" alt="User Image">
                <div class="comment-text">
                    <span class="username">
                        Maria Gonzales
                        <span class="text-muted float-right">8:03 PM Today</span>
                    </span>
                    It is a long established fact that a reader will be distracted
                    by the readable content of a page when looking at its layout.
                </div>

            </div>

            <div class="card-comment">

                <img class="img-circle img-sm" src="../dist/img/user5-128x128.jpg" alt="User Image">
                <div class="comment-text">
                    <span class="username">
                        Nora Havisham
                        <span class="text-muted float-right">8:03 PM Today</span>
                    </span>
                    The point of using Lorem Ipsum is that it hrs a morer-less
                    normal distribution of letters, as opposed to using
                    'Content here, content here', making it look like readable English.
                </div>

            </div>

        </div>

        <div class="card-footer" style="display: block;">
            <form action="#" method="post">
                <img class="img-fluid img-circle img-sm" src="../dist/img/user4-128x128.jpg" alt="Alt Text">

                <div class="img-push">
                    <input type="text" class="form-control form-control-sm" placeholder="Press enter to post comment">
                </div>
            </form>
        </div>

    </div>

</div>

</div>