<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<!-- Content Header (Page header) -->

<section class="content">

    <div class="card card-info card-outline">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h1 class="card-title">Todas las citas del SysClinica</h1>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Paciente</th>
                                    <th>N° Expediente</th>
                                    <th>Paciente</th>
                                    <th>Como ingresa</th>
                                    <th>Ocupación</th>
                                    <th>Fecha Nacimiento</th>
                                    <th>Fecha</th>
                                    <th>Timpo</th>
                                    <th>Acción</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                foreach ($this->citas as $obj) { ?>
                                    <tr>
                                        <td>

                                            <div class="info">
                                                <a href="#" class="d-block"><?= $obj->getUbicacion() ?></a>
                                            </div>
                                        </td>
                                        <td><?= $obj->getEstado() ?></td>
                                        </td>
                                        <td>Otro datos</td>
                                        <td><?= $obj->getFecha() ?></td>
                                        <td>Ejemoplo</td>
                                        <td>Ejemoplo</td>
                                        <td>
                                            <?= $obj->getFechaCaptura() ?>
                                        </td>
                                        <td><?= $obj->getObservaciones() ?>
                                        </td>
                                        <td>
                                            <div class="input-group-prepend">
                                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                    Action
                                                </button>

                                                <a class="dropdown-item" href="">Citas</a>
                                                <a class="dropdown-item" href="#">Prestamos</a>
                                                <a class="dropdown-item" href="#">Pago</a>
                                                <a class="dropdown-item" href="#">Traslados</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item" href="#">Familiares</a>
                                            </div>
                    </div>

                    </td>
                    </tr>
                <?php } ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th>Paciente</th>
                        <th>N° Expediente</th>
                        <th>Paciente</th>
                        <th>Como ingresa</th>
                        <th>Ocupación</th>
                        <th>Fecha Nacimiento</th>
                        <th>Fecha del Expedidte</th>
                        <th>Dias</th>
                        <th>Acción</th>
                    </tr>
                </tfoot>
                </table>
                </div>
                <!-- /.card-body -->
            </div>

            <div class="modal fade" id="modal-xl">
                <div class="modal-dialog modal-xl">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Abrir expediente selecciondo...</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div id="content-modal">
                                <p>One fine body&hellip;</p>
                            </div>
                        </div>
                        <div class="modal-footer justify-content-between">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
        </div>
        <!-- /.modal -->
    </div>
    <!-- ./row -->
    </div><!-- /.container-fluid -->
</section>