<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<!-- Content Header (Page header) -->
<section class="content">
    <div class="card card-info card-outline">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h1 class="card-title">CONSENTIMIENTO INFORMADO</h1>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        sdds
                    </div>
                    <!-- /.card-body -->
                </div>

                <div class="modal fade" id="modal-xl">
                    <div class="modal-dialog modal-xl">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">CONSENTIMIENTO INFORMADO</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p>One fine body&hellip;</p>
                            </div>
                            <div class="modal-footer justify-content-between">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-primary">Save changes</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
            </div>
            <!-- /.modal -->
        </div>
        <!-- ./row -->
    </div><!-- /.container-fluid -->
</section>