<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

$title =  $this->translate('Nuevo Ingreso'); # page title
# meta keywords
$this->headMeta()->appendName('keywords', 'Traslado, Rescate, Pacientes');
# meta description
$this->headMeta()->appendName('description', 'Nuevos Traslados de Pacientes');
# page title
$this->headTitle($this->escapeHtml($title));


#form
$form = $this->form;
$this->form->prepare();
$form->setAttribute('action', $this->url('ingreso-alta'));  #oops

?>
<!-- Content Header (Page header) -->
<?= $this->form()->openTag($form); ?>
<div class="card card-info card-outline">
    <div class="card-header">
        <h3 class="card-title">
            <i class="fas fa-edit"></i>
            Ingresos del Nuevo paciente...
        </h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-3">
                <!-- text input -->
                <?= $this->formHidden($form->get('idPacientes')); ?>
                <?= $this->formLabel($form->get('nombreCompleto')); ?>
                <div class="form-group">
                    <?= $this->formText($form->get('nombreCompleto')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('nombreCompleto')); ?>
                </div>
            </div>

            <div class="col-2">
                <?= $this->formLabel($form->get('sexo')); ?>
                <div class="form-group">
                    <?= $this->formSelect($form->get('sexo')); ?>
                </div>
            </div>
            <div class="text-danger">
                <?= $this->formElementErrors($form->get('sexo')); ?>
            </div>

            <div class="col-3">
                <?= $this->formLabel($form->get('fechaNac')); ?>
                <div class="form-group">
                    <?= $this->formDateSelect($form->get('fechaNac')); ?>
                </div>
            </div>
            <div class="text-danger">
                <?= $this->formElementErrors($form->get('fechaNac')); ?>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <?= $this->formLabel($form->get('escolardiad')); ?>
                    <?= $this->formText($form->get('escolardiad')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('escolardiad')); ?>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <?= $this->formLabel($form->get('ocupacion')); ?>
                    <?= $this->formText($form->get('ocupacion')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('ocupacion')); ?>
                </div>
            </div>
            <div class="col-md-5">
                <div class="form-group">
                    <?= $this->formLabel($form->get('direccion')); ?>
                    <?= $this->formText($form->get('direccion')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('direccion')); ?>
                </div>
            </div>
            <div class="col-3">
                <?= $this->formLabel($form->get('estadoCivil')); ?>
                <div class="form-group">
                    <?= $this->formSelect($form->get('estadoCivil')); ?>
                </div>
            </div>
            <div class="text-danger">
                <?= $this->formElementErrors($form->get('estadoCivil')); ?>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <?= $this->formLabel($form->get('nacionalidad')); ?>
                    <?= $this->formText($form->get('nacionalidad')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('nacionalidad')); ?>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <?= $this->formLabel($form->get('estado')); ?>
                    <?= $this->formText($form->get('estado')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('estado')); ?>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <?= $this->formLabel($form->get('municipio')); ?>
                    <?= $this->formText($form->get('municipio')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('municipio')); ?>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <?= $this->formLabel($form->get('codigoPostal')); ?>
                    <?= $this->formText($form->get('codigoPostal')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('codigoPostal')); ?>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <?= $this->formLabel($form->get('telefono')); ?>
                    <?= $this->formText($form->get('telefono')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('telefono')); ?>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <?= $this->formLabel($form->get('celular')); ?>
                    <?= $this->formText($form->get('celular')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('celular')); ?>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <?= $this->formLabel($form->get('telefonoTrabajo')); ?>
                    <?= $this->formText($form->get('telefonoTrabajo')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('telefonoTrabajo')); ?>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <?= $this->formLabel($form->get('serviciosMedicos')); ?>
                    <?= $this->formSelect($form->get('serviciosMedicos')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('serviciosMedicos')); ?>
                </div>
            </div>
        </div>
        <hr>
        </hr>
        <div class="card-footer">
            <h3>Tipo de Ingreso del Paciente</h3>
        </div>

        <div class="row">
            <div class="col-4">
                <!-- text input -->
                <?= $this->formHidden($form->get('idIngresos')); ?>
                <?= $this->formLabel($form->get('tipoIngreso')); ?>
                <div class="form-group">
                    <?= $this->formSelect($form->get('tipoIngreso')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('tipoIngreso')); ?>
                </div>
            </div>
            <div class="col-4">
                <!-- text input -->
                <?= $this->formLabel($form->get('referencia')); ?>
                <div class="form-group">
                    <?= $this->formSelect($form->get('referencia')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('referencia')); ?>
                </div>
            </div>
            <div class="col-4">
                <!-- text input -->
                <?= $this->formLabel($form->get('acude')); ?>
                <div class="form-group">
                    <?= $this->formSelect($form->get('acude')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('acude')); ?>
                </div>
            </div>
        </div>


        <hr>
        </hr>
        <div class="card-footer">
            <h3>Familiares</h3>
        </div>
        <div class="row">
            <div class="col-4">
                <!-- text input -->
                <?= $this->formHidden($form->get('idFamiliares')); ?>
                <?= $this->formHidden($form->get('idFamiliares')); ?>
                <?= $this->formHidden($form->get('Pacientes_idPacientes')); ?>
                <?= $this->formLabel($form->get('nombreCompletoF')); ?>
                <div class="form-group">
                    <?= $this->formText($form->get('nombreCompletoF')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('nombreCompletoF')); ?>
                </div>
            </div>
            <div class="col-4">
                <!-- text input -->
                <?= $this->formLabel($form->get('domicilio')); ?>
                <div class="form-group">
                    <?= $this->formText($form->get('domicilio')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('domicilio')); ?>
                </div>
            </div>
            
            <div class="col-4">
                <!-- text input -->
                <?= $this->formLabel($form->get('colonia')); ?>
                <div class="form-group">
                    <?= $this->formText($form->get('colonia')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('colonia')); ?>
                </div>
            </div>
            <div class="col-4">
                <!-- text input -->
                <?= $this->formLabel($form->get('telefonoF')); ?>
                <div class="form-group">
                    <?= $this->formText($form->get('telefonoF')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('telefonoF')); ?>
                </div>
            </div>
            <div class="col-4">
                <!-- text input -->
                <?= $this->formLabel($form->get('celularF')); ?>
                <div class="form-group">
                    <?= $this->formText($form->get('celularF')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('celularF')); ?>
                </div>
            </div>
            <div class="col-4">
                <!-- text input -->
                <?= $this->formLabel($form->get('telefonoTrabajoF')); ?>
                <div class="form-group">
                    <?= $this->formText($form->get('telefonoTrabajoF')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('telefonoTrabajoF')); ?>
                </div>
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <?= $this->formSubmit($form->get('btnGuardar')); ?>
                <button type="button" id="btnCerrar1" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>


        <div class="card-body">
            <button type="button" class="btn btn-success toastrDefaultSuccess">
                Launch Success Toast
            </button>
            <button type="button" class="btn btn-info toastrDefaultInfo">
                Launch Info Toast
            </button>
            <button type="button" class="btn btn-danger toastrDefaultError">
                Launch Error Toast
            </button>
            <button type="button" class="btn btn-warning toastrDefaultWarning">
                Launch Warning Toast
            </button>
            <div class="text-muted mt-3">
                For more examples look at <a href="https://codeseven.github.io/toastr/">https://codeseven.github.io/toastr/</a>
            </div>
        </div>
        <!-- /.card -->
    </div>
    <?= $this->form()->closeTag(); ?>

    <script>
        $(function() {
            //Initialize Select2 Elements
            $('.select2').select2()

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            })

            //Datemask dd/mm/yyyy
            $('#datemask').inputmask('dd/mm/yyyy', {
                'placeholder': 'dd/mm/yyyy'
            })
            //Datemask2 mm/dd/yyyy
            $('#datemask2').inputmask('mm/dd/yyyy', {
                'placeholder': 'mm/dd/yyyy'
            })
            //Money Euro
            $('[data-mask]').inputmask()

            //Date picker
            $('#reservationdate').datetimepicker({
                format: 'L'
            });

            //Date and time picker
            $('#reservationdatetime').datetimepicker({
                icons: {
                    time: 'far fa-clock'
                }
            });

            //Date range picker
            $('#reservation').daterangepicker()
            //Date range picker with time picker
            $('#reservationtime').daterangepicker({
                timePicker: true,
                timePickerIncrement: 30,
                locale: {
                    format: 'MM/DD/YYYY hh:mm A'
                }
            })
            //Date range as a button
            $('#daterange-btn').daterangepicker({
                    ranges: {
                        'Today': [moment(), moment()],
                        'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                        'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                        'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                        'This Month': [moment().startOf('month'), moment().endOf('month')],
                        'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                    },
                    startDate: moment().subtract(29, 'days'),
                    endDate: moment()
                },
                function(start, end) {
                    $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
                }
            )

            //Timepicker
            $('#timepicker').datetimepicker({
                format: 'LT'
            })

            //Bootstrap Duallistbox
            $('.duallistbox').bootstrapDualListbox()

            //Colorpicker
            $('.my-colorpicker1').colorpicker()
            //color picker with addon
            $('.my-colorpicker2').colorpicker()

            $('.my-colorpicker2').on('colorpickerChange', function(event) {
                $('.my-colorpicker2 .fa-square').css('color', event.color.toString());
            })

            $("input[data-bootstrap-switch]").each(function() {
                $(this).bootstrapSwitch('state', $(this).prop('checked'));
            })

        })
        // BS-Stepper Init
        document.addEventListener('DOMContentLoaded', function() {
            window.stepper = new Stepper(document.querySelector('.bs-stepper'))
        })

        // DropzoneJS Demo Code Start
        Dropzone.autoDiscover = false

        // Get the template HTML and remove it from the doumenthe template HTML and remove it from the doument
        var previewNode = document.querySelector("#template")
        previewNode.id = ""
        var previewTemplate = previewNode.parentNode.innerHTML
        previewNode.parentNode.removeChild(previewNode)

        var myDropzone = new Dropzone(document.body, { // Make the whole body a dropzone
            url: "/target-url", // Set the url
            thumbnailWidth: 80,
            thumbnailHeight: 80,
            parallelUploads: 20,
            previewTemplate: previewTemplate,
            autoQueue: false, // Make sure the files aren't queued until manually added
            previewsContainer: "#previews", // Define the container to display the previews
            clickable: ".fileinput-button" // Define the element that should be used as click trigger to select files.
        })

        myDropzone.on("addedfile", function(file) {
            // Hookup the start button
            file.previewElement.querySelector(".start").onclick = function() {
                myDropzone.enqueueFile(file)
            }
        })

        // Update the total progress bar
        myDropzone.on("totaluploadprogress", function(progress) {
            document.querySelector("#total-progress .progress-bar").style.width = progress + "%"
        })

        myDropzone.on("sending", function(file) {
            // Show the total progress bar when upload starts
            document.querySelector("#total-progress").style.opacity = "1"
            // And disable the start button
            file.previewElement.querySelector(".start").setAttribute("disabled", "disabled")
        })

        // Hide the total progress bar when nothing's uploading anymore
        myDropzone.on("queuecomplete", function(progress) {
            document.querySelector("#total-progress").style.opacity = "0"
        })

        // Setup the buttons for all transfers
        // The "add files" button doesn't need to be setup because the config
        // `clickable` has already been specified.
        document.querySelector("#actions .start").onclick = function() {
            myDropzone.enqueueFiles(myDropzone.getFilesWithStatus(Dropzone.ADDED))
        }
        document.querySelector("#actions .cancel").onclick = function() {
            myDropzone.removeAllFiles(true)
        }
        // DropzoneJS Demo Code End
    </script>