<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="row">
    <div class="col-md-8">
        <div class="card card-widget">
            <div class="card-header">
                <div class="user-block">
                    <img class="img-circle" src="/sysclinica/public/dist/img/shopping-cart.png" alt="User Image">
                    <span class="username"><a href="#">Venta del sistema</a></span>
                    <span class="description">Seleciona un proucto o un sevicio para realizar la venta
                    </span>

                </div>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="card-body" style="display: block;">
                <div class="row">
                    <?php
                    foreach ($this->productos as $obj) {
                    ?>
                        <!-- Costo de tratamiento $500 -->
                        <div class="col-lg-3 col-6">
                            <div class="small-box bg-info">
                                <a href="<?= $this->url('editar', ['action' => 'editar', 'id' => $obj->getIdproductos()]); ?>" class="small-box">
                                    <div class="inner">
                                        <h3>$<?= $obj->getPrecio() ?></h3>
                                        <p><?= $obj->getNombre() ?></p>
                                    </div>
                                </a>

                                <div class="icon">
                                    <i class="ion ion-bag"></i>
                                </div>
                                <span class="small-box-footer"><?= $obj->getTipo() ?></span>

                            </div>
                        </div>
                    <?php } ?>
                    <button type="button" id="addProduct">Agregar Producto</button>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">

        <div class="card card-widget">
            <div class="card-header">
                <div class="user-block">
                    <img class="img-circle" src="/sysclinica/public/dist/img/LogoRenovacion.png" alt="User Image">
                    <span class="username"><a href="#">Agregar servicio</a></span>
                    <span class="description">Utimo agregados 10:00 am</span>
                </div>

                <div class="card-tools">

                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>

                </div>

            </div>

            <div class="card-body" style="display: block;">
                <div id="addconte">
                    
                </div>
                <div id="productos">
                   
                    <!-- Aquí se agregarán dinámicamente los productos -->
                </div>

            </div>
            <div class="attachment-block clearfix">
                <img class="attachment-img" src="../dist/img/photo1.png" alt="Attachment Image">
                <div class="attachment-pushed">
                    <h4 class="attachment-heading"><a href="https://www.lipsum.com/">Detalle de la venta</a></h4>
                    <div class="attachment-text">
                        <table id="expedientesTable" class="table">
                            <thead>
                                <tr>
                                    <th>Sub Total</th>
                                    <th>$00.00</th>
                                    
                                    <!-- Agrega más encabezados según tus propiedades -->
                                </tr>
                                <tr>
                                    <th>I..V.A</th>
                                    <th>$00.00</th>
                                    <th></th>
                                    <!-- Agrega más encabezados según tus propiedades -->
                                </tr>
                                <tr>
                                    <th>Total</th>
                                    <th>$00.00</th>
                                    <th></th>
                                    <!-- Agrega más encabezados según tus propiedades -->
                                </tr>
                            </thead>
                            <tbody>
                                <!-- Los datos se llenarán aquí -->
                            </tbody>
                        </table>
                        <button name="btnProcesar" class="btn btn-info">Procesar Venta</button>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>